process.env.DATABASE_URL='postgres://geserd:pw@127.0.0.1:5432/geserd';process.env.SECRET_KEY='x';
Object.assign(process.env,{ROBOKASSA_LOGIN:'geserd',ROBOKASSA_TEST:'0',ROBOKASSA_PASS1:'p1',ROBOKASSA_PASS2:'p2',ROBOKASSA_HASH:'md5'});
const R=require('path').join(__dirname,'..')+'/';
const express=require('express');const {q,pool}=require(R+'src/db');const c=require('crypto');
const RK=require(R+'src/billing/robokassa');const B=require(R+'src/billing');
const app=express();app.set('trust proxy',1);app.use(express.json());
const GEO=require(R+'src/geo');app.get('/api/geo',GEO.info);app.use('/api',GEO.enforce);
app.use('/api/auth',require(R+'src/routes/auth'));app.use('/api/account',require(R+'src/routes/account'));
app.use('/api/billing',express.urlencoded({extended:false}),require(R+'src/routes/billing'));
const md5=s=>c.createHash('md5').update(s).digest('hex');
const sha=s=>c.createHash('sha256').update(s).digest('hex');
let ok=0,bad=0;const T=(n,v)=>{if(v){ok++;console.log('ok  ',n)}else{bad++;console.log('FAIL',n)}};
(async()=>{
 await q('delete from users where email like $1',['t_%@example.com']);
 const mk=async(e)=>{const[u]=await q('insert into users(email) values($1) returning id',[e]);const tok=c.randomBytes(8).toString('hex');await q("insert into sessions(token_hash,user_id,expires_at) values($1,$2,now()+interval '1 day')",[sha(tok),u.id]);return{id:u.id,ck:'gs_sid='+tok}};
 const A=await mk('t_a@example.com'),Bu=await mk('t_b@example.com');
 const s=app.listen(3998);const base='http://127.0.0.1:3998/api';
 const call=async(p,o={},u=A,ip)=>{const h={'Content-Type':'application/json',Cookie:u.ck};if(ip)h['X-Forwarded-For']=ip;const r=await fetch(base+p,{method:o.method||'GET',headers:h,body:o.body?JSON.stringify(o.body):undefined,redirect:'manual'});let j;const t=await r.text();try{j=JSON.parse(t)}catch{j=t}return{s:r.status,j,h:r.headers}};
 let r=await call('/billing/checkout',{method:'POST',body:{plan:'pro'}});T('checkout before onboarding rejected',r.s===400&&r.j.error==='onboarding_required');
 r=await call('/account/onboarding',{method:'POST',body:{name:'Anna',country:'IN'}});T('blocked country rejected at onboarding',r.s===400&&r.j.error==='invalid_country');
 r=await call('/account/onboarding',{method:'POST',body:{name:'Anna',country:'XX'}});T('unknown country rejected',r.s===400);
 r=await call('/account/onboarding',{method:'POST',body:{name:'',country:'SE'}});T('empty name rejected',r.s===400&&r.j.error==='invalid_name');
 r=await call('/account/onboarding',{method:'POST',body:{name:'Anna',country:'se'}});T('onboarding SE ok',r.s===200&&r.j.region==='eu'&&r.j.currency==='RUB');
 r=await call('/account/onboarding',{method:'POST',body:{name:'Anna',country:'RU'}});T('region locked after onboarding',r.s===409&&r.j.error==='region_locked');
 r=await call('/auth/me');T('me has region and onboarded',r.j.region==='eu'&&r.j.onboarded===true&&r.j.display==='EUR'&&JSON.stringify(r.j.login_methods)==='["github","google","email"]');
 r=await call('/account/onboarding',{method:'POST',body:{name:'Boris',country:'RU'}},Bu);T('onboarding RU ok',r.s===200&&r.j.region==='ru');
 r=await call('/auth/me',{},Bu);T('RU login methods yandex+email',JSON.stringify(r.j.login_methods)==='["yandex","email"]'&&r.j.display==='RUB');
 r=await call('/auth/regions');T('regions endpoint',r.s===200&&r.j.regions.ru&&r.j.groups.europe.includes('SE')&&!!r.j.blocked.length);
 r=await call('/billing/checkout',{method:'POST',body:{plan:'free'}});T('invalid plan rejected',r.s===400&&r.j.error==='invalid_plan');
 r=await call('/billing/checkout',{method:'POST',body:{plan:'pro',recurring:true,lang:'ru'}});
 T('checkout returns robokassa url',r.s===200&&r.j.url.startsWith('https://auth.robokassa.ru/Merchant/Index.aspx?'));
 const u=new URL(r.j.url),inv=Number(u.searchParams.get('InvId'));
 T('payment signature = md5(login:sum:inv:pass1:shp)',u.searchParams.get('SignatureValue')===md5('geserd:790.00:'+inv+':p1:shp_user='+A.id));
 T('Recurring flag + culture ru',u.searchParams.get('Recurring')==='true'&&u.searchParams.get('Culture')==='ru');
 const cb=(id,sum,pass,extra={})=>{const shp={shp_user:A.id,...extra};const sv=md5(sum+':'+id+':'+pass+':shp_user='+A.id);return new URLSearchParams({OutSum:sum,InvId:String(id),SignatureValue:sv,...shp}).toString()};
 const post=async(body,ip)=>{const h={'Content-Type':'application/x-www-form-urlencoded'};if(ip)h['X-Forwarded-For']=ip;const x=await fetch(base+'/billing/robokassa/result',{method:'POST',headers:h,body});return{s:x.status,t:await x.text()}};
 let x=await post(cb(inv,'790.00','WRONG'));T('wrong signature rejected, plan unchanged',x.s===400&&(await q('select plan from users where id=$1',[A.id]))[0].plan==='free');
 x=await post(cb(inv,'100.00','p2'));T('wrong amount rejected',x.s===400&&(await q('select status from invoices where id=$1',[inv]))[0].status==='pending');
 x=await post(cb(inv,'790.00','p2'),'49.36.10.1');T('result accepted even from a geo-blocked IP, answers OK<id>',x.s===200&&x.t==='OK'+inv);
 let sub=(await q('select * from subscriptions where user_id=$1',[A.id]))[0];
 T('plan upgraded to pro, subscription recurring with parent',(await q('select plan from users where id=$1',[A.id]))[0].plan==='pro'&&sub.recurring&&sub.parent_invoice_id===inv&&sub.status==='active');
 const days=(new Date(sub.current_period_end)-Date.now())/864e5;T('period is 30 days',days>29.9&&days<30.1);
 x=await post(cb(inv,'790.00','p2'));T('replay is idempotent (OK, no second period)',x.t==='OK'+inv&&(await q('select current_period_end e from subscriptions where user_id=$1',[A.id]))[0].e.getTime()===new Date(sub.current_period_end).getTime());
 T('notification created once',(await q("select count(*)::int n from notifications where user_id=$1 and title='billing_paid'",[A.id]))[0].n===1);
 r=await call('/billing');T('billing summary',r.j.plan==='pro'&&r.j.invoices.some(i=>i.id===inv&&i.status==='paid')&&r.j.provider.configured===true&&r.j.display==='EUR'&&r.j.prices.business===2490);
 r=await call('/billing/quote',{method:'POST',body:{plan:'business'}});T('upgrade quote has proration credit',r.s===200&&r.j.kind==='change'&&r.j.credit>=780&&r.j.amount===Math.max(10,2490-r.j.credit));
 r=await call('/billing/quote',{method:'POST',body:{plan:'free'}});T('downgrade to free via checkout refused',r.s===400);
 await q("update subscriptions set current_period_end=now()+interval '20 days' where user_id=$1",[A.id]);
 const calls=[];global.fetch=new Proxy(global.fetch,{apply(t,th,a){if(String(a[0]).includes('Merchant/Recurring')){calls.push(a[1].body.toString());return Promise.resolve(new Response('OK+'+(calls.length),{status:200}))}return t.apply(th,a)}});
 await B.tick();T('no renewal attempted 20 days before the end',calls.length===0);
 await q("update subscriptions set current_period_end=now()+interval '10 hours' where user_id=$1",[A.id]);
 await B.tick();T('renewal charge sent once, 10h before the end',calls.length===1);
 const rp=new URLSearchParams(calls[0]);const rinv=Number(rp.get('InvoiceID'));
 T('recurring request: previous invoice + signature md5(login:sum:inv:pass1)',rp.get('PreviousInvoiceID')===String(inv)&&rp.get('SignatureValue')===md5('geserd:790.00:'+rinv+':p1'));
 await B.tick();T('no double charge while renewal pending',calls.length===1);
 x=await post(new URLSearchParams({OutSum:'790.00',InvId:String(rinv),SignatureValue:md5('790.00:'+rinv+':p2'),shp_user:A.id}).toString().replace('shp_user='+A.id,'shp_user='+A.id));
 T('shp mismatch (not signed) rejected',x.s===400);
 x=await post(new URLSearchParams({OutSum:'790.00',InvId:String(rinv),SignatureValue:md5('790.00:'+rinv+':p2')}).toString());T('renewal callback without shp accepted',x.s===200);
 sub=(await q('select * from subscriptions where user_id=$1',[A.id]))[0];const left=(new Date(sub.current_period_end)-Date.now())/864e5;
 T('renewal extends from the old end (about 30.4 days)',left>30.2&&left<30.6&&sub.parent_invoice_id===inv);
 r=await call('/billing/cancel',{method:'POST'});sub=(await q('select * from subscriptions where user_id=$1',[A.id]))[0];T('cancel keeps access, stops auto-renew',r.s===200&&!sub.recurring&&sub.cancel_at_period_end);
 await q("update subscriptions set current_period_end=now()+interval '5 hours' where user_id=$1",[A.id]);const n0=calls.length;await B.tick();T('cancelled subscription is not charged',calls.length===n0);
 r=await call('/billing/resume',{method:'POST'});T('resume before the end ok',r.s===200&&(await q('select recurring from subscriptions where user_id=$1',[A.id]))[0].recurring);
 global.fetch=new Proxy(global.fetch,{apply(t,th,a){if(String(a[0]).includes('Merchant/Recurring'))return Promise.resolve(new Response('ERROR',{status:200}));return t.apply(th,a)}});
 await q("update invoices set status='failed' where user_id=$1 and status='pending'",[A.id]);
 await q("update subscriptions set current_period_end=now()+interval '5 hours',attempts=0,next_attempt_at=null where user_id=$1",[A.id]);
 await B.tick();sub=(await q('select * from subscriptions where user_id=$1',[A.id]))[0];T('failed charge: attempt 1 scheduled for +1 day, still active',sub.attempts===1&&sub.status==='active'&&sub.next_attempt_at>new Date(Date.now()+20*36e5));
 for(let i=0;i<2;i++){await q("update subscriptions set next_attempt_at=now()-interval '1 minute' where user_id=$1",[A.id]);await B.tick()}
 sub=(await q('select * from subscriptions where user_id=$1',[A.id]))[0];T('3 failed attempts -> past_due',sub.attempts===3&&sub.status==='past_due');
 await q("update subscriptions set current_period_end=now()-interval '4 days' where user_id=$1",[A.id]);await B.tick();
 T('after grace the account drops to free, subscription canceled',(await q('select plan from users where id=$1',[A.id]))[0].plan==='free'&&(await q('select status from subscriptions where user_id=$1',[A.id]))[0].status==='canceled');
 r=await call('/billing/checkout',{method:'POST',body:{plan:'business',recurring:false}},A);const u2=new URL(r.j.url);T('one-time checkout has no Recurring flag, amount 2490',!u2.searchParams.has('Recurring')&&u2.searchParams.get('OutSum')==='2490.00');
 r=await call('/billing',{},Bu);T('other user sees none of these invoices',r.j.invoices.length===0&&r.j.plan==='free');
 const sx=await fetch(base+'/billing/robokassa/success?OutSum=790.00&InvId='+inv+'&SignatureValue='+md5('790.00:'+inv+':p1:shp_user='+A.id)+'&shp_user='+A.id,{redirect:'manual'});T('success page verifies Password1 and redirects',sx.status===302&&sx.headers.get('location')==='/app/settings/billing/?paid='+inv);
 const sf=await fetch(base+'/billing/robokassa/success?OutSum=790.00&InvId='+inv+'&SignatureValue=bad',{redirect:'manual'});T('success with bad signature does not confirm',sf.headers.get('location').includes('check='));
 s.close();console.log(ok+' passed, '+bad+' failed');await q('delete from users where email like $1',['t_%@example.com']);await pool.end();process.exit(bad?1:0)
})().catch(e=>{console.error(e);process.exit(2)});
