process.env.DATABASE_URL='postgres://geserd:pw@127.0.0.1:5432/geserd';process.env.SECRET_KEY='ab'.repeat(32);process.env.BROADCAST_GAP_MS='0';
const R=require('path').join(__dirname,'..')+'/';
const express=require('express');const {q,pool}=require(R+'src/db');const c=require('crypto');
const mailer=require(R+'src/mailer');const sent=[];mailer.transport.sendMail=async o=>{sent.push(o);return{accepted:o.to}};
const B=require(R+'src/broadcast');const GEO=require(R+'src/geo');
const app=express();app.set('trust proxy',1);app.use(express.json());app.use('/api',GEO.enforce);
app.use('/api/audiences',require(R+'src/routes/audiences'));app.use('/api/broadcasts',require(R+'src/routes/broadcasts'));app.use('/api/unsubscribe',require(R+'src/routes/unsubscribe'));app.use('/api/templates',require(R+'src/routes/templates'));
const sha=s=>c.createHash('sha256').update(s).digest('hex');
let ok=0,bad=0;const T=(n,v)=>{if(v){ok++;console.log('ok  ',n)}else{bad++;console.log('FAIL',n)}};
(async()=>{
 await q("delete from users where email like 'tb_%@example.com'");
 const mk=async(e,plan)=>{const[u]=await q('insert into users(email,plan,onboarded_at) values($1,$2,now()) returning id',[e,plan]);const tok=c.randomBytes(8).toString('hex');await q("insert into sessions(token_hash,user_id,expires_at) values($1,$2,now()+interval '1 day')",[sha(tok),u.id]);await q("insert into subdomains(slug,user_id) values($1,$2)",['tb'+tok.slice(0,8),u.id]);return{id:u.id,ck:'gs_sid='+tok,slug:'tb'+tok.slice(0,8)}};
 const A=await mk('tb_a@example.com','pro'),F=await mk('tb_f@example.com','free'),X=await mk('tb_x@example.com','pro');
 const s=app.listen(3997);const base='http://127.0.0.1:3997/api';
 const call=async(p,o={},u=A)=>{const h={Cookie:u.ck};if(o.body&&!o.form)h['Content-Type']='application/json';if(o.form)h['Content-Type']='application/x-www-form-urlencoded';if(o.ip)h['X-Forwarded-For']=o.ip;if(o.nocookie)delete h.Cookie;const r=await fetch(base+p,{method:o.method||'GET',headers:h,body:o.form?o.form:o.body?JSON.stringify(o.body):undefined});const t=await r.text();let j;try{j=JSON.parse(t)}catch{j=t}return{s:r.status,j,h:r.headers}};
 let r=await call('/audiences',{method:'POST',body:{name:'  Newsletter '}});const aud=r.j.id;T('create audience',r.s===201&&r.j.name==='Newsletter');
 r=await call('/audiences',{method:'POST',body:{name:''}});T('empty audience name rejected',r.s===400);
 const fa=(await call('/audiences',{method:'POST',body:{name:'a'}},F)).j.id;r=await call('/audiences',{method:'POST',body:{name:'b'}},F);T('free plan: second audience refused',r.s===403&&r.j.error==='limit_reached'&&r.j.resource==='audiences');
 r=await call('/audiences/'+aud+'/contacts',{method:'POST',body:{email:'Anna@Example.org',first_name:'Anna'}});T('add one contact, email lowercased',r.s===201&&r.j.added===1);
 r=await call('/audiences/'+aud+'/contacts',{method:'POST',body:{email:'anna@example.org',last_name:'Smith'}});T('same email is not duplicated, name merged',r.s===201&&r.j.added===0&&r.j.existing===1);
 const csv='Email;First Name;Last name\n"bob@example.org";Bob;"O;Brien"\ncarl@example.org;=1+1;\nnot-an-email;X;Y\nbob@example.org;Bob;Dup\n';
 r=await call('/audiences/'+aud+'/contacts',{method:'POST',body:{csv}});T('csv import: semicolons, quotes, invalid and duplicate rows counted',r.s===201&&r.j.added===2&&r.j.invalid===1&&r.j.duplicates===1);
 r=await call('/audiences/'+aud+'/contacts?q=brien');T('search by part of the last name',r.s===200&&r.j.total===1&&r.j.data[0].email==='bob@example.org'&&r.j.data[0].last_name==="O;Brien");
 r=await call('/audiences/'+aud+'/contacts?limit=2&offset=0');T('pagination',r.j.data.length===2&&r.j.total===3);
 const ex=await fetch(base+'/audiences/'+aud+'/export',{headers:{Cookie:A.ck}});const txt=await ex.text();T('csv export: header, 3 rows, formula cell neutralised',ex.headers.get('content-type').startsWith('text/csv')&&txt.trim().split('\n').length===4&&txt.includes("'=1+1"));
 const many=Array.from({length:101},(_,i)=>({email:'m'+i+'@example.org'}));
  r=await call('/audiences/'+fa+'/contacts',{method:'POST',body:{contacts:many}},F);T('free plan: 101 contacts exceed the limit of 100',r.s===403&&r.j.resource==='contacts');
 r=await call('/audiences/'+aud,{},X);T('other user cannot see the audience',r.s===404);
 r=await call('/broadcasts',{method:'POST',body:{name:'Autumn',audience_id:aud,from:'Acme <news@'+A.slug+'.geserd.com>',subject:'Hi {{first_name}}',html:'<p>Hello {{first_name}} {{last_name}}</p>',text:'Hello {{first_name}}'}});const bid=r.j.id;T('create draft',r.s===201&&r.j.status==='draft'&&r.j.audience_name==='Newsletter');
 r=await call('/broadcasts',{method:'POST',body:{name:'x',audience_id:'11111111-1111-1111-1111-111111111111'}});T('foreign/unknown audience rejected',r.s===404&&r.j.error==='audience_not_found');
 r=await call('/broadcasts',{method:'POST',body:{name:'x',from:'nope'}});T('bad from rejected',r.s===400&&r.j.error==='invalid_from');
 r=await call('/broadcasts/'+bid+'/test',{method:'POST',body:{to:'me@example.com'}});T('test email sent with [Test] subject and personalization',r.s===200&&sent.length===1&&sent[0].subject==='[Test] Hi Test'&&/Unsubscribe/.test(sent[0].html));
 sent.length=0;
 const nd=await call('/broadcasts',{method:'POST',body:{name:'nodomain',audience_id:aud,from:'a@unverified-domain.com',subject:'s',text:'t'}});
 r=await call('/broadcasts/'+nd.j.id+'/send',{method:'POST',body:{}});T('unverified domain refused',r.s===403&&r.j.error==='domain_not_verified');
 const em=(await call('/audiences',{method:'POST',body:{name:'empty'}})).j.id;
 const eb=await call('/broadcasts',{method:'POST',body:{name:'emptyaud',audience_id:em,from:'a@'+A.slug+'.geserd.com',subject:'s',text:'t'}});
 r=await call('/broadcasts/'+eb.j.id+'/send',{method:'POST',body:{}});T('empty audience refused',r.s===400&&r.j.error==='audience_empty');
 r=await call('/broadcasts/'+bid+'/send',{method:'POST',body:{scheduled_at:new Date(Date.now()+1000).toISOString()}});T('schedule in the past/too soon refused',r.s===400&&r.j.error==='invalid_schedule');
 r=await call('/broadcasts/'+bid+'/send',{method:'POST',body:{}});T('send starts, 3 recipients',r.s===200&&r.j.status==='sending'&&r.j.total===3);
 r=await call('/broadcasts/'+bid,{method:'PATCH',body:{subject:'new'}});T('sending broadcast is not editable',r.s===409);
 await B.tick();
 r=await call('/broadcasts/'+bid);T('all 3 sent, status sent',r.j.status==='sent'&&r.j.sent===3&&r.j.failed===0&&sent.length===3);
 const mAnna=sent.find(x=>x.to[0]==='anna@example.org');
 T('personalized subject and html',mAnna.subject==='Hi Anna'&&/Hello Anna Smith/.test(mAnna.html));
 const lu=mAnna.headers['List-Unsubscribe'],tk=/api\/unsubscribe\/([^>]+)>/.exec(lu)[1];
 T('List-Unsubscribe and One-Click headers present',/^<https:\/\/geserd\.com\/api\/unsubscribe\//.test(lu)&&mAnna.headers['List-Unsubscribe-Post']==='List-Unsubscribe=One-Click');
 T('footer link in html and text uses the page url',/geserd\.com\/unsubscribe\/\?t=/.test(mAnna.html)&&/Unsubscribe: https:\/\/geserd\.com\/unsubscribe/.test(mAnna.text));
 r=await call('/unsubscribe/'+tk,{nocookie:true});T('unsubscribe info without login, email masked',r.s===200&&r.j.email==='an***@example.org'&&r.j.unsubscribed===false&&r.j.audience==='Newsletter');
 r=await call('/unsubscribe/'+tk.slice(0,-1)+(tk.slice(-1)==='a'?'b':'a'),{nocookie:true});T('tampered token rejected',r.s===404);
 r=await call('/unsubscribe/'+tk,{method:'POST',form:'List-Unsubscribe=One-Click',nocookie:true,ip:'49.36.10.1'});T('one-click POST works for a geo-blocked IP too',r.s===200&&r.j.unsubscribed===true);
 r=await call('/audiences/'+aud+'/contacts?status=unsubscribed');T('contact marked unsubscribed in the dashboard',r.j.total===1&&r.j.data[0].email==='anna@example.org');
 sent.length=0;
 const b2=(await call('/broadcasts/'+bid+'/duplicate',{method:'POST'})).j;T('duplicate creates a draft copy',b2.status==='draft'&&/copy/.test(b2.name));
 await call('/broadcasts/'+b2.id+'/send',{method:'POST',body:{}});await B.tick();
 r=await call('/broadcasts/'+b2.id);T('second broadcast skips the unsubscribed contact',r.j.status==='sent'&&r.j.sent===2&&r.j.total===2&&!sent.some(x=>x.to[0]==='anna@example.org'));
 r=await call('/unsubscribe/'+tk+'/resubscribe',{method:'POST',nocookie:true});T('resubscribe works',r.j.unsubscribed===false);
 await q("update contacts set unsubscribed=false where audience_id=$1",[aud]);
 await q("insert into suppressions(user_id,address,reason) values($1,'carl@example.org','bounced')",[A.id]);sent.length=0;
 const b3=(await call('/broadcasts/'+bid+'/duplicate',{method:'POST'})).j;await call('/broadcasts/'+b3.id+'/send',{method:'POST',body:{}});await B.tick();
 r=await call('/broadcasts/'+b3.id);T('suppressed address is skipped, not failed',r.j.sent===2&&r.j.skipped===1&&r.j.failed===0);
 const q8=fa;
 await call('/audiences/'+q8+'/contacts',{method:'POST',body:{contacts:Array.from({length:8},(_,i)=>({email:'q'+i+'@example.org'}))}},F);
 const fb=(await call('/broadcasts',{method:'POST',body:{name:'quota',audience_id:q8,from:'a@'+F.slug+'.geserd.com',subject:'s',text:'t'}},F)).j;
 sent.length=0;await call('/broadcasts/'+fb.id+'/send',{method:'POST',body:{}},F);await B.tick();
 r=await call('/broadcasts/'+fb.id,{},F);T('free plan daily quota (5) pauses the broadcast with a resume time',r.j.status==='paused'&&r.j.sent===5&&r.j.pending===3&&!!r.j.resume_at&&r.j.error==='quota_exceeded');
 await B.tick();r=await call('/broadcasts/'+fb.id,{},F);T('paused broadcast does not run before resume time',r.j.sent===5);
 await q("update emails set created_at=created_at-interval '2 days' where user_id=$1",[F.id]);await q("update broadcasts set resume_at=now()-interval '1 minute' where id=$1",[fb.id]);
 await B.tick();r=await call('/broadcasts/'+fb.id,{},F);T('after the quota resets it resumes and finishes',r.j.status==='sent'&&r.j.sent===8);
 const sch=(await call('/broadcasts',{method:'POST',body:{name:'later',audience_id:aud,from:'a@'+A.slug+'.geserd.com',subject:'s',text:'t'}})).j;
 r=await call('/broadcasts/'+sch.id+'/send',{method:'POST',body:{scheduled_at:new Date(Date.now()+3600e3).toISOString()}});T('schedule one hour ahead',r.j.status==='scheduled');
 sent.length=0;await B.tick();T('scheduled broadcast does not start early',sent.length===0);
 r=await call('/broadcasts/'+sch.id,{method:'DELETE'});T('scheduled broadcast cannot be deleted before cancel',r.s===409&&r.j.error==='cancel_first');
 r=await call('/broadcasts/'+sch.id+'/cancel',{method:'POST'});T('cancel scheduled',r.j.status==='canceled');
 const sch2=(await call('/broadcasts',{method:'POST',body:{name:'due',audience_id:aud,from:'a@'+A.slug+'.geserd.com',subject:'s',text:'t'}})).j;
 await call('/broadcasts/'+sch2.id+'/send',{method:'POST',body:{scheduled_at:new Date(Date.now()+3600e3).toISOString()}});await q("update broadcasts set scheduled_at=now()-interval '1 minute' where id=$1",[sch2.id]);
 sent.length=0;await B.tick();r=await call('/broadcasts/'+sch2.id);T('due scheduled broadcast starts and completes',r.j.status==='sent'&&r.j.sent===2&&r.j.skipped===1);
 r=await call('/audiences/'+aud,{method:'DELETE'});T('audience with finished broadcasts can be deleted and keeps its name on broadcasts',r.s===200&&(await q('select audience_name from broadcasts where id=$1',[bid]))[0].audience_name==='Newsletter');
 r=await call('/broadcasts/'+bid,{},X);T('other user cannot read the broadcast',r.s===404);
 r=await call('/broadcasts/'+bid,{method:'DELETE'});T('delete finished broadcast',r.s===200);
 s.close();console.log(ok+' passed, '+bad+' failed');await q("delete from users where email like 'tb_%@example.com'");await pool.end();process.exit(bad?1:0)
})().catch(e=>{console.error(e);process.exit(2)});
