process.env.DATABASE_URL='postgres://geserd:pw@127.0.0.1:5432/geserd';process.env.SECRET_KEY='ab'.repeat(32);
const R=require('path').join(__dirname,'..')+'/';
const express=require('express');const {q,pool}=require('../src/db');const c=require('crypto');
const {emit}=require(R+'src/events');const M=require(R+'src/metrics');const AL=require(R+'src/apilog');const BS=require(R+'src/bstats');
const app=express();app.set('trust proxy',1);app.use(express.json());
app.use('/api/metrics',require(R+'src/routes/metrics'));app.use('/api/logs',require(R+'src/routes/logs'));app.use('/api/usage',require(R+'src/routes/usage'));app.use('/api/broadcasts',require(R+'src/routes/broadcasts'));
const sha=s=>c.createHash('sha256').update(s).digest('hex');
let ok=0,bad=0;const T=(n,v)=>{if(v){ok++;console.log('ok  ',n)}else{bad++;console.log('FAIL',n)}};
(async()=>{
 const srv=app.listen(0);const base='http://127.0.0.1:'+srv.address().port;
 const call=async(p,o)=>{const r=await fetch(base+p,o);const t=await r.text();let j;try{j=JSON.parse(t)}catch{j=t}return{s:r.status,j,h:r.headers}};
 await q("delete from users where email like 'tm_%@example.com'");
 const mk=async(e,plan)=>{const[u]=await q('insert into users(email,plan,onboarded_at) values($1,$2,now()) returning id',[e,plan]);const tok=c.randomBytes(8).toString('hex'),kt='gs_'+c.randomBytes(16).toString('hex');await q("insert into sessions(token_hash,user_id,expires_at) values($1,$2,now()+interval '1 day')",[sha(tok),u.id]);const[k]=await q("insert into api_keys(user_id,name,prefix,key_hash) values($1,'Prod',$2,$3) returning id",[u.id,kt.slice(0,7),sha(kt)]);return{id:u.id,ck:{cookie:'gs_sid='+tok},key:{authorization:'Bearer '+kt},keyId:k.id}};
 const A=await mk('tm_a@example.com','pro'),B=await mk('tm_b@example.com','free'),Z=await mk('tm_z@example.com','business');
 const mail=async(u,o)=>{const id=c.randomUUID();await q("insert into emails(id,user_id,direction,from_addr,to_addrs,subject,message_id,status) values($1,$2,$3,$4,$5,$6,$7,'queued')",[id,u.id,o.dir||'out',o.from||'hi@a.com',JSON.stringify(o.to||['x@gmail.com']),o.subject||'Hello',id]);return id};
 const e1=await mail(A,{to:['x@gmail.com','y@yahoo.com']});
 await emit(e1,'sent',{accepted:['x@gmail.com','y@yahoo.com'],suppressed:['z@bad.com']});
 await emit(e1,'delivered',{recipient:'x@gmail.com',dsn:'2.0.0'});
 await emit(e1,'bounced',{recipient:'y@yahoo.com',dsn:'5.1.1',detail:'user unknown'});
 const e2=await mail(A,{from:'news@b.org',to:['q@gmail.com']});
 await emit(e2,'sent',{accepted:['q@gmail.com'],suppressed:[]});
 await emit(e2,'delivered',{recipient:'q@gmail.com',dsn:'2.0.0'});
 await emit(e2,'complained',{recipient:'q@gmail.com'});
 await emit(e2,'delayed',{recipient:'q@gmail.com',dsn:'4.2.2'});
 const e3=await mail(A,{to:['a@x.com','b@x.com','c@x.com']});await emit(e3,'failed',{error:'boom'});
 const e4=await mail(A,{dir:'in',from:'ext@z.com',to:['support@a.com']});await emit(e4,'received',{from:'ext@z.com'});
 let r=await call('/api/metrics?days=7',{headers:A.ck});
 T('metrics 200',r.s===200);
 T('series length 7 daily',r.j.series.length===7&&r.j.bucket==='day');
 T('sent counted per accepted recipient',r.j.totals.sent===3);
 T('delivered 2',r.j.totals.delivered===2);
 T('bounced 1',r.j.totals.bounced===1);
 T('complained 1',r.j.totals.complained===1);
 T('delayed 1',r.j.totals.delayed===1);
 T('failed counts recipients',r.j.totals.failed===3);
 T('suppressed 1',r.j.totals.suppressed===1);
 T('received 1',r.j.totals.received===1);
 T('today bucket holds data',r.j.series[6].sent===3);
 T('rate delivered 66.67',r.j.rates.delivered===66.67);
 T('rate bounced 33.33',r.j.rates.bounced===33.33);
 T('health none under 20 sends',r.j.health==='none');
 T('recipient domains listed',r.j.recipients.some(x=>x.domain==='gmail.com'&&x.delivered===2));
 T('bounce reason dsn',r.j.bounces.length===1&&r.j.bounces[0].dsn==='5.1.1'&&r.j.bounces[0].n===1);
 T('domains list',r.j.domains.includes('a.com')&&r.j.domains.includes('b.org'));
 T('prev null when no room',r.j.prev&&typeof r.j.prev.totals.sent==='number');
 T('no-store header',/no-store/.test(r.h.get('cache-control')||''));
 r=await call('/api/metrics?days=7&domain=b.org',{headers:A.ck});
 T('domain filter sent 1',r.j.totals.sent===1&&r.j.totals.complained===1&&r.j.totals.bounced===0);
 T('domain filter recipients scoped',r.j.recipients.length===1&&r.j.bounces.length===0);
 r=await call('/api/metrics?days=7&domain=all',{headers:A.ck});T('domain all',r.j.totals.sent===3);
 r=await call('/api/metrics?days=7&domain=%27%3Bdrop',{headers:A.ck});T('bad domain ignored',r.s===200&&r.j.totals.sent===3);
 r=await call('/api/metrics?days=1',{headers:A.ck});
 T('24h hourly 24 buckets',r.j.bucket==='hour'&&r.j.series.length===24&&r.j.totals.sent===3);
 r=await call('/api/metrics?days=90',{headers:A.ck});
 T('pro capped to 30',r.j.days===30&&r.j.capped===true&&r.j.max_days===30);
 T('pro ranges list',JSON.stringify(r.j.ranges)==='[1,7,15,30]');
 r=await call('/api/metrics?days=90',{headers:B.ck});
 T('free capped to 7',r.j.days===7&&r.j.capped===true);
 T('free empty is zero',r.j.totals.sent===0&&r.j.health==='none'&&r.j.rates.delivered===null);
 r=await call('/api/metrics?days=365',{headers:Z.ck});T('business capped to 90',r.j.days===90);
 r=await call('/api/metrics?days=abc',{headers:A.ck});T('invalid days defaults 15',r.j.days===15&&!r.j.capped);
 r=await call('/api/metrics?days=7',{headers:{}});T('unauthorized',r.s===401);
 r=await call('/api/metrics?days=7',{headers:A.key});T('key cannot read metrics',r.s===403||r.s===401);
 r=await call('/api/metrics?days=7',{headers:B.ck});T('isolation',r.j.totals.sent===0&&r.j.domains.length===0);
 const W=M.windowOf(7,new Date('2026-10-09T13:45:00Z'));
 T('window daily start',W.start.toISOString()==='2026-10-03T00:00:00.000Z'&&W.end.toISOString()==='2026-10-10T00:00:00.000Z');
 const W1=M.windowOf(1,new Date('2026-10-09T13:45:00Z'));
 T('window hourly',W1.start.toISOString()==='2026-10-08T14:00:00.000Z'&&W1.end.toISOString()==='2026-10-09T14:00:00.000Z');
 const mkT=(s,b,cp)=>({sent:s,bounced:b,complained:cp,delivered:s-b});
 T('health none under 20',M.health(mkT(10,5,0))==='none');
 T('health good',M.health(mkT(1000,10,0))==='good');
 T('health warn bounce',M.health(mkT(1000,50,0))==='warn');
 T('health warn complaint',M.health(mkT(10000,0,10))==='warn');
 T('health bad complaint',M.health(mkT(1000,0,4))==='bad');
 T('score null under 20',M.score(mkT(10,0,0))===null);
 T('score 100 when clean',M.score(mkT(1000,0,0))===100);
 T('score drops with bounce',M.score(mkT(1000,40,0))===70);
 T('score floor 0',M.score(mkT(1000,500,100))===0);
 T('score in report',r.j.score===null);
 await q("insert into metric_hours(user_id,hr,domain,sent,delivered) values($1,now()-interval '3 days','old.com',50,50)",[A.id]);
 await q("insert into metric_hours(user_id,hr,domain,sent,delivered) values($1,now()-interval '40 days','ancient.com',50,50)",[A.id]);
 await q("insert into metric_hours(user_id,hr,domain,sent,delivered) values($1,now()-interval '9 days','prev.com',50,50)",[A.id]);
 await M.prune();
 const[an]=await q("select count(*)::int n from metric_hours where user_id=$1 and domain='ancient.com'",[A.id]),[rc]=await q("select count(*)::int n from metric_hours where user_id=$1 and domain='old.com'",[A.id]);
 T('prune removes beyond plan',an.n===0&&rc.n===1);
 r=await call('/api/metrics?days=7',{headers:A.ck});T('prev window computed for pro 7d',r.j.prev&&r.j.prev.totals.sent===50&&r.j.totals.sent===53);
 await q('delete from api_logs where user_id=$1',[A.id]);
 const k1=await call('/api/usage',{headers:A.key});T('key request ok',k1.s===200);
 const k2=await call('/api/usage',{headers:{authorization:'Bearer gs_nope'}});T('bad key 401',k2.s===401);
 await new Promise(x=>setTimeout(x,300));
 let L=await call('/api/logs?kind=requests',{headers:A.ck});
 T('request logged',L.s===200&&L.j.data.length===1&&L.j.data[0].method==='GET'&&L.j.data[0].path==='/api/usage'&&L.j.data[0].status===200);
 T('log has key name',L.j.data[0].key_name==='Prod');
 await call('/api/usage',{headers:A.ck});await new Promise(x=>setTimeout(x,200));
 L=await call('/api/logs?kind=requests',{headers:A.ck});T('session requests not logged',L.j.total===1);
 await AL.record({uid:A.id,keyId:A.keyId,method:'POST',path:'/api/emails',status:422,ms:12,ip:'1.2.3.4',ua:'node',req:{from:'a@a.com',to:['b@b.com'],html:'x'.repeat(5000),authorization:'Bearer secret',attachments:[{filename:'a.pdf',content:'A'.repeat(4000)}]},res:{error:'domain_not_verified'}});
 await new Promise(x=>setTimeout(x,1100));
 await AL.record({uid:A.id,keyId:A.keyId,method:'SMTP',path:'submission',status:250,ms:40,via:'smtp',req:{subject:'=cmd'},res:{id:'1'}});
 await new Promise(x=>setTimeout(x,1100));
 await AL.record({uid:A.id,keyId:null,method:'POST',path:'/api/emails',status:500,ms:3,req:{},res:{error:'server_error'}});
 L=await call('/api/logs?kind=requests',{headers:A.ck});T('three or more logged',L.j.total>=4);
 L=await call('/api/logs?kind=requests&status=4xx',{headers:A.ck});T('filter 4xx',L.j.total===1&&L.j.data[0].status===422);
 L=await call('/api/logs?kind=requests&status=5xx',{headers:A.ck});T('filter 5xx',L.j.total===1);
 L=await call('/api/logs?kind=requests&status=422',{headers:A.ck});T('filter exact',L.j.total===1);
 L=await call('/api/logs?kind=requests&method=SMTP',{headers:A.ck});T('filter SMTP',L.j.total===1&&L.j.data[0].via==='smtp');
 L=await call('/api/logs?kind=requests&q=usage',{headers:A.ck});T('filter path search',L.j.total===1);
 L=await call('/api/logs?kind=requests&q=%25',{headers:A.ck});T('wildcard escaped',L.j.total===0);
 L=await call('/api/logs?kind=requests&limit=2',{headers:A.ck});T('paginates',L.j.data.length===2&&L.j.next>0);
 const L2=await call('/api/logs?kind=requests&limit=2&before='+L.j.next,{headers:A.ck});T('next page distinct',L2.j.data.length>=1&&L2.j.data.every(x=>!L.j.data.some(y=>y.id===x.id)));
 const all=await call('/api/logs?kind=requests',{headers:A.ck});const post=all.j.data.find(x=>x.status===422);
 const D=await call('/api/logs/requests/'+post.id,{headers:A.ck});
 T('detail 200',D.s===200&&D.j.res.error==='domain_not_verified');
 T('authorization hidden',D.j.req.authorization==='[hidden]');
 T('long html truncated',/chars\]$/.test(D.j.req.html)&&D.j.req.html.length<700);
 T('attachment content summarised',/^\[\d+ bytes\]$/.test(D.j.req.attachments[0].content));
 const D2=await call('/api/logs/requests/'+post.id,{headers:B.ck});T('detail isolated',D2.s===404);
 const D3=await call('/api/logs/requests/abc',{headers:A.ck});T('detail bad id',D3.s===404);
 const Bx=await call('/api/logs?kind=requests',{headers:B.ck});T('logs isolated',Bx.j.total===0);
 T('free retention 1 day',Bx.j.retention_days===1&&L.j.retention_days===7);
 const big=await call('/api/logs?kind=requests&days=999',{headers:A.ck});T('days capped to retention',big.j.days===7);
 const k3=await call('/api/logs?kind=requests',{headers:A.key});T('key cannot read logs',k3.s===403||k3.s===401);
 const X=await call('/api/logs/export?kind=requests',{headers:A.ck});
 T('export csv',X.s===200&&/text\/csv/.test(X.h.get('content-type'))&&/^time,method,path,status,ms,via,key,ip/.test(X.j));
 const ef=await mail(A,{subject:'=SUM(1)'});await emit(ef,'sent',{accepted:['x@gmail.com']});const XF=await call('/api/logs/export?kind=events&type=sent&q=SUM',{headers:A.ck});T('export neutralises formulas',/"?'=SUM\(1\)/.test(XF.j)&&!/,=SUM/.test(XF.j));
 let E=await call('/api/logs?kind=events',{headers:A.ck});
 T('events listed',E.s===200&&E.j.total===10);
 E=await call('/api/logs?kind=events&type=bounced',{headers:A.ck});T('events type filter',E.j.total===1&&E.j.data[0].dsn==='5.1.1'&&E.j.data[0].recipient==='y@yahoo.com');
 E=await call('/api/logs?kind=events&direction=in',{headers:A.ck});T('events direction filter',E.j.total===1&&E.j.data[0].type==='received');
 E=await call('/api/logs?kind=events&domain=b.org',{headers:A.ck});T('events domain filter',E.j.total===4);
 E=await call('/api/logs?kind=events&domain=a.com&direction=in',{headers:A.ck});T('inbound domain uses recipient',E.j.total===1);
 E=await call('/api/logs?kind=events&q=yahoo',{headers:A.ck});T('events search recipient',E.j.total>=2);
 E=await call('/api/logs?kind=events&q=nothing-here',{headers:A.ck});T('events search empty',E.j.total===0);
 E=await call('/api/logs?kind=events&limit=4',{headers:A.ck});T('events paginate',E.j.data.length===4&&E.j.next>0);
 const E2=await call('/api/logs?kind=events&limit=100&before='+E.j.next,{headers:A.ck});T('events next page',E2.j.data.length===6);
 E=await call('/api/logs?kind=events',{headers:B.ck});T('events isolated',E.j.total===0);
 const XE=await call('/api/logs/export?kind=events&type=bounced',{headers:A.ck});T('events export',XE.s===200&&/y@yahoo\.com/.test(XE.j)&&XE.j.split('\n').length===3);
 const[aud]=await q("insert into audiences(user_id,name) values($1,'List') returning id",[A.id]);
 const cts=[];for(const n of['c1','c2','c3','c4','c5']){const[x]=await q("insert into contacts(audience_id,user_id,email) values($1,$2,$3) returning id",[aud.id,A.id,n+'@m.com']);cts.push(x.id)}
 const[bc]=await q("insert into broadcasts(user_id,audience_id,audience_name,name,status,sent,started_at) values($1,$2,'List','Launch','sent',4,now()-interval '1 hour') returning id",[A.id,aud.id]);
 const evm=[];for(let i=0;i<4;i++){const id=await mail(A,{to:['c'+(i+1)+'@m.com'],subject:'Launch'});evm.push(id);await q("insert into broadcast_recipients(broadcast_id,contact_id,email,status,email_id) values($1,$2,$3,'sent',$4)",[bc.id,cts[i],'c'+(i+1)+'@m.com',id])}
 await q("insert into broadcast_recipients(broadcast_id,contact_id,email,status,error) values($1,$2,'c5@m.com','skipped','unsubscribed')",[bc.id,cts[4]]);
 await emit(evm[0],'delivered',{recipient:'c1@m.com',dsn:'2.0.0'});await emit(evm[1],'delivered',{recipient:'c2@m.com',dsn:'2.0.0'});await emit(evm[1],'complained',{recipient:'c2@m.com'});
 await emit(evm[2],'bounced',{recipient:'c3@m.com',dsn:'5.1.1',detail:'no such user'});
 await q("update contacts set unsubscribed=true,unsubscribed_at=now() where id=$1",[cts[0]]);
 let S=await call('/api/broadcasts/'+bc.id+'/stats',{headers:A.ck});
 T('stats 200',S.s===200);
 T('stats counts',S.j.sent===4&&S.j.delivered===2&&S.j.bounced===1&&S.j.complained===1);
 T('stats in transit',S.j.in_transit===1);
 T('stats unsubscribed attributed',S.j.unsubscribed===1&&S.j.unsub_list[0].email==='c1@m.com');
 T('stats rates',S.j.rates.delivered===50&&S.j.rates.bounced===25&&S.j.rates.complained===25&&S.j.rates.unsubscribed===25);
 T('stats skipped',S.j.skipped===1);
 T('stats reasons',S.j.reasons[0].dsn==='5.1.1'&&S.j.bounce_list[0].email==='c3@m.com');
 T('stats complaint list',S.j.complaint_list[0].email==='c2@m.com');
 T('stats timeline',S.j.timeline.length>=1&&S.j.timeline[0].delivered===2);
 T('stats not archived',S.j.archived===false);
 const[b2]=await q("insert into broadcasts(user_id,audience_id,audience_name,name,status,sent,started_at) values($1,$2,'List','Later','sent',1,now()) returning id",[A.id,aud.id]);
 const em5=await mail(A,{to:['c1@m.com']});await q("insert into broadcast_recipients(broadcast_id,contact_id,email,status,email_id) values($1,$2,'c1@m.com','sent',$3)",[b2.id,cts[0],em5]);
 await q("update contacts set unsubscribed_at=now()+interval '1 minute' where id=$1",[cts[0]]);
 S=await call('/api/broadcasts/'+bc.id+'/stats',{headers:A.ck});T('unsubscribe goes to latest broadcast',S.j.unsubscribed===0);
 const S2=await call('/api/broadcasts/'+b2.id+'/stats',{headers:A.ck});T('latest broadcast gets it',S2.j.unsubscribed===1);
 await q("update contacts set unsubscribed_at=now()-interval '2 hours' where id=$1",[cts[0]]);
 S=await call('/api/broadcasts/'+bc.id+'/stats',{headers:A.ck});T('older unsubscribe not attributed',S.j.unsubscribed===0);
 await q("delete from emails where id=any($1)",[evm]);
 S=await call('/api/broadcasts/'+bc.id+'/stats',{headers:A.ck});
 T('archived snapshot after purge',S.j.archived===true&&S.j.delivered===2&&S.j.bounced===1);
 const S3=await call('/api/broadcasts/'+bc.id+'/stats',{headers:B.ck});T('stats isolated',S3.s===404);
 const S4=await call('/api/broadcasts/nope/stats',{headers:A.ck});T('stats bad id',S4.s===404);
 await BS.snapshot();T('snapshot job runs',true);
 await q("delete from users where email like 'tm_%@example.com'");
 console.log(ok+' passed, '+bad+' failed');srv.close();await pool.end();process.exit(bad?1:0)
})().catch(e=>{console.error(e);process.exit(1)});
