create extension if not exists pgcrypto;
create table if not exists users(id uuid primary key default gen_random_uuid(),email text unique not null,name text,plan text not null default 'free',country text,created_at timestamptz not null default now());
create table if not exists oauth_accounts(provider text not null,provider_uid text not null,user_id uuid not null references users on delete cascade,primary key(provider,provider_uid));
create table if not exists login_codes(email text primary key,code_hash text not null,attempts int not null default 0,expires_at timestamptz not null);
create table if not exists sessions(token_hash text primary key,user_id uuid not null references users on delete cascade,ip text,expires_at timestamptz not null,created_at timestamptz not null default now());
create table if not exists api_keys(id uuid primary key default gen_random_uuid(),user_id uuid not null references users on delete cascade,name text not null,prefix text not null,key_hash text unique not null,created_at timestamptz not null default now(),last_used_at timestamptz,revoked_at timestamptz);
create table if not exists domains(id uuid primary key default gen_random_uuid(),user_id uuid not null references users on delete cascade,name text not null,status text not null default 'pending',sending_ok boolean not null default false,receiving_ok boolean not null default false,dkim_selector text not null,dkim_public text not null,dkim_private_enc text not null,created_at timestamptz not null default now(),verified_at timestamptz);
create unique index if not exists domains_verified_name on domains(name) where status='verified';
create index if not exists domains_user on domains(user_id);
create table if not exists emails(id uuid primary key default gen_random_uuid(),user_id uuid not null references users on delete cascade,domain_id uuid references domains on delete set null,api_key_id uuid references api_keys on delete set null,direction text not null check(direction in('out','in')),from_addr text not null,to_addrs jsonb not null,subject text,html text,text_body text,message_id text,in_reply_to text,status text not null default 'queued',error text,created_at timestamptz not null default now());
create index if not exists emails_user_time on emails(user_id,created_at desc);
create table if not exists events(id bigserial primary key,email_id uuid references emails on delete cascade,type text not null,data jsonb,created_at timestamptz not null default now());
create table if not exists suppressions(user_id uuid not null references users on delete cascade,address text not null,reason text not null,created_at timestamptz not null default now(),primary key(user_id,address));
create table if not exists webhooks(id uuid primary key default gen_random_uuid(),user_id uuid not null references users on delete cascade,url text not null,secret text not null,events text[] not null default '{}',active boolean not null default true,created_at timestamptz not null default now());
create table if not exists subdomains(slug text primary key,user_id uuid not null references users on delete cascade,created_at timestamptz not null default now());
create index if not exists subdomains_user on subdomains(user_id);
create index if not exists emails_user_dir_time on emails(user_id,direction,created_at desc);
create table if not exists contact_messages(id uuid primary key default gen_random_uuid(),name text,email text not null,topic text not null,message text not null,ip text,user_id uuid references users on delete set null,created_at timestamptz not null default now());
create table if not exists mail_queue(queue_id text primary key,email_id uuid not null references emails on delete cascade,created_at timestamptz not null default now());
create index if not exists mail_queue_time on mail_queue(created_at);
create table if not exists kv(key text primary key,value text not null);
create index if not exists events_email on events(email_id);
alter table emails add column if not exists attachments jsonb;
alter table emails add column if not exists headers jsonb;
create index if not exists emails_msgid on emails(message_id);
create table if not exists webhook_deliveries(id bigserial primary key,webhook_id uuid not null references webhooks on delete cascade,event text not null,payload jsonb not null,status text not null default 'pending',attempts int not null default 0,next_at timestamptz not null default now(),last_status int,last_error text,created_at timestamptz not null default now(),delivered_at timestamptz);
create index if not exists whd_due on webhook_deliveries(next_at) where status='pending';
create index if not exists whd_hook on webhook_deliveries(webhook_id,created_at desc);
alter table emails add column if not exists spam_score numeric(5,2);
alter table emails add column if not exists spam_rules jsonb;
