const express=require('express');const {q}=require('./db');
const app=express();app.set('trust proxy',1);app.use('/api/emails',express.json({limit:'15mb'}));app.use(express.json({limit:'1mb'}));
const GEO=require('./geo');
app.get('/api/geo/check',GEO.check);
app.get('/api/geo',GEO.info);
app.use('/api',GEO.enforce);
app.get('/api/health',async(_,res)=>{try{await q('select 1');res.json({ok:true})}catch{res.status(503).json({ok:false})}});
app.use('/api/auth',require('./routes/auth'));
app.use('/api/api-keys',require('./routes/keys'));
app.use('/api/domains',require('./routes/domains'));
app.use('/api/emails',require('./routes/emails'));
app.use('/api/subdomain',require('./routes/subdomain'));
app.use('/api/usage',require('./routes/usage'));
app.use('/api/metrics',require('./routes/metrics'));
app.use('/api/logs',require('./routes/logs'));
app.use('/api/webhooks',require('./routes/webhooks'));
app.use('/api/contact',require('./routes/contact'));
app.use('/api/templates',require('./routes/templates'));
app.use('/api/audiences',require('./routes/audiences'));
app.use('/api/broadcasts',require('./routes/broadcasts'));
app.use('/api/unsubscribe',require('./routes/unsubscribe'));
app.use('/api/settings',require('./routes/settings'));
app.use('/api/auth-kit',require('./routes/authkit'));
app.use('/api/account',require('./routes/account'));
app.use('/api/notifications',require('./routes/notifications'));
app.use('/api/tickets',require('./routes/tickets'));
app.use('/api/admin',require('./routes/admin'));
app.use('/api/billing',express.urlencoded({extended:false,limit:'20kb'}),require('./routes/billing'));
app.get('/api/status',async(_,res)=>{try{res.set('Cache-Control','public,max-age=15');res.json(await require('./status').report())}catch(e){console.error('status',e.message);res.status(503).json({error:'unavailable'})}});
app.get('/api/smtp',(_,res)=>res.json(require('./smtp').state));
app.use('/api',(_,res)=>res.status(404).json({error:'not_found'}));
app.use((e,_q,res,_n)=>{console.error(e);res.status(500).json({error:'server_error'})});
const PL=require('./plans');
setInterval(()=>{for(const[p,v]of Object.entries(PL))q("delete from emails e using users u where e.user_id=u.id and u.plan=$1 and e.created_at<now()-($2||' days')::interval",[p,String(v.logDays)]).catch(e=>console.error('retention',e.message))},3600000).unref();
const housekeeping=()=>{require('./bstats').snapshot().then(()=>require('./metrics').prune()).then(()=>require('./apilog').prune()).catch(e=>console.error('housekeeping',e.message))};
setInterval(housekeeping,3600000).unref();setTimeout(housekeeping,60000).unref();
const port=process.env.PORT||3001;app.listen(port,'127.0.0.1',()=>console.log('geserd api on 127.0.0.1:'+port));
require('./mailevents').start();
require('./inbound').start();
require('./webhooks').start();
require('./smtp').start();
require('./status').start();
require('./billing').start();
require('./broadcast').startWorker();
